dummy_cronjobs = {
'cron1 - script 0' : True,
'cron2 - script 1': False,
'cron3 - script 2': False,
'cron4 - Remidner Script': False,
'cron5 - Report Fetching Script':False,
'cron6 - Web Scrapper 0':True,
'cron7 - Web Scrapper 1':False,
'cron8 - Auto Dispo Script 1':False,
'cron9 - Auto Dispo Script 3':False,
'cron10 - Web Scrapper 3':False,
'cron11 - Yield Calculation':True,
'cron12 - Hardware Check 1':False,
'cron13 - Hardware Check 2':True,
'cron14 - SPC Report 1':False,
'cron15 - SPC Report 12':True,
'cron16 - term report running at sever01':False}